# feature_extraction.py

import logging
import numpy as np
import torch
from torch import nn
from typing import Dict, List, Tuple
from scipy.signal import butter, lfilter
from scipy import stats
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.utils import shuffle
from scipy.stats import norm
from scipy.stats import kurtosis
from scipy.stats import skew
from scipy.stats import entropy
from scipy.stats import variation
from scipy.stats import iqr
from scipy.stats import mode
from scipy.stats import median_abs_deviation
from scipy.stats import gmean
from scipy.stats import hmean
from scipy.stats import trim_mean
from scipy.stats import tmean
from scipy.stats import tmax
from scipy.stats import tmin
from scipy.stats import kstest
from scipy.stats import linregress
from scipy.stats import pearsonr
from scipy.stats import spearmanr
from scipy.stats import pointbiserialr
from scipy.stats import kendalltau
from scipy.stats import mstats
from scipy.stats import circmean
from scipy.stats import circstd
from scipy.stats import circvar
from scipy.stats import circmode
from scipy.stats import circmedian
from scipy.stats import circnorm
from scipy.stats import circuniform
from scipy.stats import circwraparound
from scipy.stats import circmean_2d
from scipy.stats import circstd_2d
from scipy.stats import circvar_2d
from scipy.stats import circmode_2d
from scipy.stats import circmedian_2d
from scipy.stats import circnorm_2d
from scipy.stats import circuniform_2d
from scipy.stats import circwraparound_2d
from scipy.stats import circmean_3d
from scipy.stats import circstd_3d
from scipy.stats import circvar_3d
from scipy.stats import circmode_3d
from scipy.stats import circmedian_3d
from scipy.stats import circnorm_3d
from scipy.stats import circuniform_3d
from scipy.stats import circwraparound_3d
from scipy.stats import circmean_4d
from scipy.stats import circstd_4d
from scipy.stats import circvar_4d
from scipy.stats import circmode_4d
from scipy.stats import circmedian_4d
from scipy.stats import circnorm_4d
from scipy.stats import circuniform_4d
from scipy.stats import circwraparound_4d
from scipy.stats import circmean_5d
from scipy.stats import circstd_5d
from scipy.stats import circvar_5d
from scipy.stats import circmode_5d
from scipy.stats import circmedian_5d
from scipy.stats import circnorm_5d
from scipy.stats import circuniform_5d
from scipy.stats import circwraparound_5d
from scipy.stats import circmean_6d
from scipy.stats import circstd_6d
from scipy.stats import circvar_6d
from scipy.stats import circmode_6d
from scipy.stats import circmedian_6d
from scipy.stats import circnorm_6d
from scipy.stats import circuniform_6d
from scipy.stats import circwraparound_6d
from scipy.stats import circmean_7d
from scipy.stats import circstd_7d
from scipy.stats import circvar_7d
from scipy.stats import circmode_7d
from scipy.stats import circmedian_7d
from scipy.stats import circnorm_7d
from scipy.stats import circuniform_7d
from scipy.stats import circwraparound_7d
from scipy.stats import circmean_8d
from scipy.stats import circstd_8d
from scipy.stats import circvar_8d
from scipy.stats import circmode_8d
from scipy.stats import circmedian_8d
from scipy.stats import circnorm_8d
from scipy.stats import circuniform_8d
from scipy.stats import circwraparound_8d
from scipy.stats import circmean_9d
from scipy.stats import circstd_9d
from scipy.stats import circvar_9d
from scipy.stats import circmode_9d
from scipy.stats import circmedian_9d
from scipy.stats import circnorm_9d
from scipy.stats import circuniform_9d
from scipy.stats import circwraparound_9d
from scipy.stats import circmean_10d
from scipy.stats import circstd_10d
from scipy.stats import circvar_10d
from scipy.stats import circmode_10d
from scipy.stats import circmedian_10d
from scipy.stats import circnorm_10d
from scipy.stats import circuniform_10d
from scipy.stats import circwraparound_10d
from scipy.stats import circmean_11d
from scipy.stats import circstd_11d
from scipy.stats import circvar_11d
from scipy.stats import circmode_11d
from scipy.stats import circmedian_11d
from scipy.stats import circnorm_11d
from scipy.stats import circuniform_11d
from scipy.stats import circwraparound_11d
from scipy.stats import circmean_12d
from scipy.stats import circstd_12d
from scipy.stats import circvar_12d
from scipy.stats import circmode_12d
from scipy.stats import circmedian_12d
from scipy.stats import circnorm_12d
from scipy.stats import circuniform_12d
from scipy.stats import circwraparound_12d
from scipy.stats import circmean_13d
from scipy.stats import circstd_13d
from scipy.stats import circvar_13d
from scipy.stats import circmode_13d
from scipy.stats import circmedian_13d
from scipy.stats import circnorm_13d
from scipy.stats import circuniform_13d
from scipy.stats import circwraparound_13d
from scipy.stats import circmean_14d
from scipy.stats import circstd_14d
from scipy.stats import circvar_14d
from scipy.stats import circmode_14d
from scipy.stats import circmedian_14d
from scipy.stats import circnorm_14d
from scipy.stats import circuniform_14d
from scipy.stats import circwraparound_14d
from scipy.stats import circmean_15d
from scipy.stats import circstd_15d
from scipy.stats import circvar_15d
from scipy.stats import circmode_15d
from scipy.stats import circmedian_15d
from scipy.stats import circnorm_15d
from scipy.stats import circuniform_15d
from scipy.stats import circwraparound_15d
from scipy.stats import circmean_16d
from scipy.stats import circstd_16d
from scipy.stats import circvar_16d
from scipy.stats import circmode_16d
from scipy.stats import circmedian_16d
from scipy.stats import circnorm_16d
from scipy.stats import circuniform_16d
from scipy.stats import circwraparound_16d
from scipy.stats import circmean_17d
from scipy.stats import circstd_17d
from scipy.stats import circvar_17d
from scipy.stats import circmode_17d
from scipy.stats import circmedian_17d
from scipy.stats import circnorm_17d
from scipy.stats import circuniform_17d
from scipy.stats import circwraparound_17d
from scipy.stats import circmean_18d
from scipy.stats import circstd_18d
from scipy.stats import circvar_18d
from scipy.stats import circmode_18d
from scipy.stats import circmedian_18d
from scipy.stats import circnorm_18d
from scipy.stats import circuniform_18d
from scipy.stats import circwraparound_18d
from scipy.stats import circmean_19d
from scipy.stats import circstd_19d
from scipy.stats import circvar_19d
from scipy.stats import circmode_19d
from scipy.stats import circmedian_19d
from scipy.stats import circnorm_19d
from scipy.stats import circuniform_19d
from scipy.stats import circwraparound_19d
from scipy.stats import circmean_20d
from scipy.stats import circstd_20d
from scipy.stats import circvar_20d
from scipy.stats import circmode_20d
from scipy.stats import circmedian_20d
from scipy.stats import circnorm_20d
from scipy.stats import circuniform_20d
from scipy.stats import circwraparound_20d
from scipy.stats import circmean_21d
from scipy.stats import circstd_21d
from scipy.stats import circvar_21d
from scipy.stats import circmode_21d
from scipy.stats import circmedian_21d
from scipy.stats import circnorm_21d
from scipy.stats import circuniform_21d
from scipy.stats import circwraparound_21d
from scipy.stats import circmean_22d
from scipy.stats import circstd_22d
from scipy.stats import circvar_22d
from scipy.stats import circmode_22d
from scipy.stats import circmedian_22d
from scipy.stats import circnorm_22d
from scipy.stats import circuniform_22d
from scipy.stats import circwraparound_22d
from scipy.stats import circmean_23d
from scipy.stats import circstd_23d
from scipy.stats import circvar_23d
from scipy.stats import circmode_23d
from scipy.stats import circmedian_23d
from scipy.stats import circnorm_23d
from scipy.stats import circuniform_23d
from scipy.stats import circwraparound_23d
from scipy.stats import circmean_24d
from scipy.stats import circstd_24d
from scipy.stats import circvar_24d
from scipy.stats import circmode_24d
from scipy.stats import circmedian_24d
from scipy.stats import circnorm_24d
from scipy.stats import circuniform_24d
from scipy.stats import circwraparound_24d
from scipy.stats import circmean_25d
from scipy.stats import circstd_25d
from scipy.stats import circvar_25d
from scipy.stats import circmode_25d
from scipy.stats import circmedian_25d
from scipy.stats import circnorm_25d
from scipy.stats import circuniform_25d
from scipy.stats import circwraparound_25d
from scipy.stats import circmean_26d
from scipy.stats import circstd_26d
from scipy.stats import circvar_26d
from scipy.stats import circmode_26d
from scipy.stats import circmedian_26d
from scipy.stats import circnorm_26d
from scipy.stats import circuniform_26d
from scipy.stats import circwraparound_26d
from scipy.stats import circmean_27d
from scipy.stats import circstd_27d
from scipy.stats import circvar_27d
from scipy.stats import circmode_27d
from scipy.stats import circmedian_27d
from scipy.stats import circnorm_27d
from scipy.stats import circuniform_27d
from scipy.stats import circwraparound_27d
from scipy.stats import circmean_28d
from scipy.stats import circstd_28d
from scipy.stats import circvar_28d
from scipy.stats import circmode_28d
from scipy.stats import circmedian_28d
from scipy.stats import circnorm_28d
from scipy.stats import circuniform_28d
from scipy.stats import circwraparound_28d
from scipy.stats import circmean_29d
from scipy.stats import circstd_29d
from scipy.stats import circvar_29d
from scipy.stats import circmode_29d
from scipy.stats import circmedian_29d
from scipy.stats import circnorm_29d
from scipy.stats import circuniform_29d
from scipy.stats import circwraparound_29d
from scipy.stats import circmean_30d
from scipy.stats import circstd_30d
from scipy.stats import circvar_30d
from scipy.stats import circmode_30d
from scipy.stats import circmedian_30d
from scipy.stats import circnorm_30d
from scipy.stats import circuniform_30d
from scipy.stats import circwraparound_30d
from scipy.stats import circmean_31d
from scipy.stats import circstd_31d
from scipy.stats import circvar_31d
from scipy.stats import circmode_31d
from scipy.stats import circmedian_31d
from scipy.stats import circnorm_31d
from scipy.stats import circuniform_31d
from scipy.stats import circwraparound_31d
from scipy.stats import circmean_32d
from scipy.stats import circstd_32d
from scipy.stats import circvar_32d
from scipy.stats import circmode_32d
from scipy.stats import circmedian_32d
from scipy.stats import circnorm_32d
from scipy.stats import circuniform_32d
from scipy.stats import circwraparound_32d
from scipy.stats import circmean_33d
from scipy.stats import circstd_33d
from scipy.stats import circvar_33d
from scipy.stats import circmode_33d
from scipy.stats import circmedian_33d
from scipy.stats import circnorm_33d
from scipy.stats import circuniform_33d
from scipy.stats import circwraparound_33d
from scipy.stats import circmean_34d
from scipy.stats import circstd_34d
from scipy.stats import circvar_34d
from scipy.stats import circmode_34d
from scipy.stats import circmedian_34d
from scipy.stats import circnorm_34d
from scipy.stats import circuniform_34d
from scipy.stats import circwraparound_34d
from scipy.stats import circmean_35d
from scipy.stats import circstd_35d
from scipy.stats import circvar_35d
from scipy.stats import circmode_35d
from scipy.stats import circmedian_35d
from scipy.stats import circnorm_35d
from scipy.stats import circuniform_35d
from scipy.stats import circwraparound_35d
from scipy.stats import circmean_36d
from scipy.stats import circstd_36d
from scipy.stats import circvar_36d
from scipy.stats import circmode_36d
from scipy.stats import circmedian_36d
from scipy.stats import circnorm_36d
from scipy.stats import circuniform_36d
from scipy.stats import circwraparound_36d
from scipy.stats import circmean_37d
from scipy.stats import circstd_37d
from scipy.stats import circvar_37d
from scipy.stats import circmode_37d
from scipy.stats import circmedian_37d
from scipy.stats import circnorm_37d
from scipy.stats import circuniform_37d
from scipy.stats import circwraparound_37d
from scipy.stats import circmean_38d
from scipy.stats import circstd_38d
from scipy.stats import circvar_38d
from scipy.stats import circmode_38d
from scipy.stats import circmedian_38d
from scipy.stats import circnorm_38d
from scipy.stats import circuniform_38d
from scipy.stats import circwraparound_38d
from scipy.stats import circmean_39d
from scipy.stats import circstd_39d
from scipy.stats import circvar_39d
from scipy.stats import circmode_39d
from scipy.stats import circmedian_39d
from scipy.stats import circnorm_39d
from scipy.stats import circuniform_39d
from scipy.stats import circwraparound_39d
from scipy.stats import circmean_40d
from scipy.stats import circstd_40d
from scipy.stats import circvar_40d
from scipy.stats import circmode_40d
from scipy.stats import circmedian_40d
from scipy.stats import circnorm_40d
from scipy.stats import circuniform_40d
from scipy.stats import circwraparound_40d
from scipy.stats import circmean_41d
from scipy.stats import circstd_41d
from scipy.stats import circvar_41d
from scipy.stats import circmode_41d
from scipy.stats import circmedian_41d
from scipy.stats import circnorm_41d
from scipy.stats import circuniform_41d
from scipy.stats import circwraparound_41d
from scipy.stats import circmean_42d
from scipy.stats import circstd_42d
from scipy.stats import circvar_42d
from scipy.stats import circmode_42d
from scipy.stats import circmedian_42d
from scipy.stats import circnorm_42d
from scipy.stats import circuniform_42d
from scipy.stats import circwraparound_42d
from scipy.stats import circmean_43d
from scipy.stats import circstd_43d
from scipy.stats import circvar_43d
from scipy.stats import circmode_43d
from scipy.stats import circmedian_43d
from scipy.stats import circnorm_43d
from scipy.stats import circuniform_43d
from scipy.stats import circwraparound_43d
from scipy.stats import circmean_44d
from scipy.stats import circstd_44d
from scipy.stats import circvar_44d
from scipy.stats import circmode_44d
from scipy.stats import circmedian_44d
from scipy.stats import circnorm_44d
from scipy.stats import circuniform_44d
from scipy.stats import circwraparound_44d
from scipy.stats import circmean_45d
from scipy.stats import circstd_45d
from scipy.stats import circvar_45d
from scipy.stats import circmode_45d
from scipy.stats import circmedian_45d
from scipy.stats import circnorm_45d
from scipy.stats import circuniform_45d
from scipy.stats import circwraparound_45d
from scipy.stats import circmean_46d
from scipy.stats import circstd_46d
from scipy.stats import circvar_46d
from scipy.stats import circmode_46d
from scipy.stats import circmedian_46d
from scipy.stats import circnorm_46d
from scipy.stats import circuniform_46d
from scipy.stats import circwraparound_46d
from scipy.stats import circmean_47d
from scipy.stats import circstd_47d
from scipy.stats import circvar_47d
from scipy.stats import circmode_47d
from scipy.stats import circmedian_47d
from scipy.stats import circnorm_47d
from scipy.stats import circuniform_47d
from scipy.stats import circwraparound_47d
from scipy.stats import circmean_48d
from scipy.stats import circstd_48d
from scipy.stats import circvar_48d
from scipy.stats import circmode_48d
from scipy.stats import circmedian_48d
from scipy.stats import circnorm_48d
from scipy.stats import circuniform_48d
from scipy.stats import circwraparound_48d
from scipy.stats import circmean_49d
from scipy.stats import circstd_49d
from scipy.stats import circvar_49d
from scipy.stats import circmode_49d
from scipy.stats import circmedian_49d
from scipy.stats import circnorm_49d
from scipy.stats import circuniform_49d
from scipy.stats import circwraparound_49d
from scipy.stats import circmean_50d
from scipy.stats import circstd_50d
from scipy.stats import circvar_50d
from scipy.stats import circmode_50d
from scipy.stats import circmedian_50d
from scipy.stats import circnorm_50d
from scipy.stats import circuniform_50d
from scipy.stats import circwraparound_50d
from scipy.stats import circmean_51d
from scipy.stats import circstd_51d
from scipy.stats import circvar_51d
from scipy.stats import circmode_51d
from scipy.stats import circmedian_51d
from scipy.stats import circnorm_51d
from scipy.stats import circuniform_51d
from scipy.stats import circwraparound_51d
from scipy.stats import circmean_52d
from scipy.stats import circstd_52d
from scipy.stats import circvar_52d
from scipy.stats import circmode_52d
from scipy.stats import circmedian_52d
from scipy.stats import circnorm_52d
from scipy.stats import circuniform_52d
from scipy.stats import circwraparound_52d
from scipy.stats import circmean_53d
from scipy.stats import circstd_53d
from scipy.stats import circvar_53d
from scipy.stats import circmode_53d
from scipy.stats import circmedian_53d
from scipy.stats import circnorm_53d
from scipy.stats import circuniform_53d
from scipy.stats import circwraparound_53d
from scipy.stats import circmean_54d
from scipy.stats import circstd_54d
from scipy.stats import circvar_54d
from scipy.stats import circmode_54d
from scipy.stats import circmedian_54d
from scipy.stats import circnorm_54d
from scipy.stats import circuniform_54d
from scipy.stats import circwraparound_54d
from scipy.stats import circmean_55d
from scipy.stats import circstd_55d
from scipy.stats import circvar_55d
from scipy.stats import circmode_55d
from scipy.stats import circmedian_55d
from scipy.stats import circnorm_55d
from scipy.stats import circuniform_55d
from scipy.stats import circwraparound_55d
from scipy.stats import circmean_56d
from scipy.stats import circstd_56d
from scipy.stats import circvar_56d
from scipy.stats import circmode_56d
from scipy.stats import circmedian_56d
from scipy.stats import circnorm_56d
from scipy.stats import circuniform_56d
from scipy.stats import circwraparound_56d
from scipy.stats import circmean_57d
from scipy.stats import circstd_57d
from scipy.stats import circvar_57d
from scipy.stats import circmode_57d
from scipy.stats import circmedian_57d
from scipy.stats import circnorm_57d
from scipy.stats import circuniform_57d
from scipy.stats import circwraparound_57d
from scipy.stats import circmean_58d
from scipy.stats import circstd_58d
from scipy.stats import circvar_58d
from scipy.stats import circmode_58d
from scipy.stats import circmedian_58d
from scipy.stats import circnorm_58d
from scipy.stats import circuniform_58d
from scipy.stats import circwraparound_58d
from scipy.stats import circmean_59d
from scipy.stats import circstd_59d
from scipy.stats import circvar_59d
from scipy.stats import circmode_59d
from scipy.stats import circmedian_59d
from scipy.stats import circnorm_59d
from scipy.stats import circuniform_59d
from scipy.stats import circwraparound_59d
from scipy.stats import circmean_60d
from scipy.stats import circstd_60d
from scipy.stats import circvar_60d
from scipy.stats import circmode_60d
from scipy.stats import circmedian_60d
from scipy.stats import circnorm_60d
from scipy.stats import circuniform_60d
from scipy.stats import circwraparound_60d
from scipy.stats import circmean_61d
from scipy.stats import circstd_61d
from scipy.stats import circvar_61d
from scipy.stats import circmode_61d
from scipy.stats import circmedian_61d
from scipy.stats import circnorm_61d
from scipy.stats import circuniform_61d
from scipy.stats import circwraparound_61d
from scipy.stats import circmean_62d
from scipy.stats import circstd_62d
from scipy.stats import circvar_62d
from scipy.stats import circmode_62d
from scipy.stats import circmedian_62d
from scipy.stats import circnorm_62d
from scipy.stats import circuniform_62d
from scipy.stats import circwraparound_62d
from scipy.stats import circmean_63d
from scipy.stats import circstd_63d
from scipy.stats import circvar_63d
from scipy.stats import circmode_63d
from scipy.stats import circmedian_63d
from scipy.stats import circnorm_63d
from scipy.stats import circuniform_63d
from scipy.stats import circwraparound_63d
from scipy.stats import circmean_64d
from scipy.stats import circstd_64d
from scipy.stats import circvar_64d
from scipy.stats import circmode_64d
from scipy.stats import circmedian_64d
from scipy.stats import circnorm_64d
from scipy.stats import circuniform_64d
from scipy.stats import circwraparound_64d
from scipy.stats import circmean_65d
from scipy.stats import circstd_65d
from scipy.stats import circvar_65d
from scipy.stats import circmode_65d
from scipy.stats import circmedian_65d
from scipy.stats import circnorm_65d
from scipy.stats import circuniform_65d
from scipy.stats import circwraparound_65d
from scipy.stats import circmean_66d
from scipy.stats import circstd_66d
from scipy.stats import circvar_66d
from scipy.stats import circmode_66d
from scipy.stats import circmedian_66d
from scipy.stats import circnorm_66d
from scipy.stats import circuniform_66d
from scipy.stats import circwraparound_66d
from scipy.stats import circmean_67d
from scipy.stats import circstd_67d
from scipy.stats import circvar_67d
from scipy.stats import circmode_67d
from scipy.stats import circmedian_67d
from scipy.stats import circnorm_67d
from scipy.stats import circuniform_67d
from scipy.stats import circwraparound_67d
from scipy.stats import circmean_68d
from scipy.stats import circstd_68d
from scipy.stats import circvar_68d
from scipy.stats import circmode_68d
from scipy.stats import circmedian_68d
from scipy.stats import circnorm_68d
from scipy.stats import circuniform_68d
from scipy.stats import circwraparound_68d
from scipy.stats import circmean_69d
from scipy.stats import circstd_69d
from scipy.stats import circvar_69d
from scipy.stats import circmode_69d
from scipy.stats import circmedian_69d
from scipy.stats import circnorm_69d
from scipy.stats import circuniform_69d
from scipy.stats import circwraparound_69d
from scipy.stats import circmean_70d
from scipy.stats import circstd_70d
from scipy.stats import circvar_70d
from scipy.stats import circmode_70d
from scipy.stats import circmedian_70d
from scipy.stats import circnorm_70d
from scipy.stats import circuniform_70d
from scipy.stats import circwraparound_70d
from scipy.stats import circmean_71d
from scipy.stats import circstd_71d
from scipy.stats import circvar_71d
from scipy.stats import circmode_71d
from scipy.stats import circmedian_71d
from scipy.stats import circnorm_71d
from scipy.stats import circuniform_71d
from scipy.stats import circwraparound_71d
from scipy.stats import circmean_72d
from scipy.stats import circstd_72d
from scipy.stats import circvar_72d
from scipy.stats import circmode_72d
from scipy.stats import circmedian_72d
from scipy.stats import circnorm_72d
from scipy.stats import circuniform_72d
from scipy.stats import circwraparound_72d
from scipy.stats import circmean_73d
from scipy.stats import circstd_73d
from scipy.stats import circvar_73d
from scipy.stats import circmode_73d
from scipy.stats import circmedian_73d
from scipy.stats import circnorm_73d
from scipy.stats import circuniform_73d
from scipy.stats import circwraparound_73d
from scipy.stats import circmean_74d
from scipy.stats import circstd_74d
from scipy.stats import circvar_74d
from scipy.stats import circmode_74d
from scipy.stats import circmedian_74d
from scipy.stats import circnorm_74d
from scipy.stats import circuniform_74d
from scipy.stats import circwraparound_74d
from scipy.stats import circmean_75d
from scipy.stats import circstd_75d
from scipy.stats import circvar_75d
from scipy.stats import circmode_75d
from scipy.stats import circmedian_75d
from scipy.stats import circnorm_75d
from scipy.stats import circuniform_75d
from scipy.stats import circwraparound_75d
from scipy.stats import circmean_76d
from scipy.stats import circstd_76d
from scipy.stats import circvar_76d
from scipy.stats import circmode_76d
from scipy.stats import circmedian_76d
from scipy.stats import circnorm_76d
from scipy.stats import circuniform_76d
from scipy.stats import circwraparound_76d
from scipy.stats import circmean_77d
from scipy.stats import circstd_77d
from scipy.stats import circvar_77d
from scipy.stats import circmode_77d
from scipy.stats import circmedian_77d
from scipy.stats import circnorm_77d
from scipy.stats import circuniform_77d
from scipy.stats import circwraparound_77d
from scipy.stats import circmean_78d
from scipy.stats import circstd_78d
from scipy.stats import circvar_78d
from scipy.stats import circmode_78d
from scipy.stats import circmedian_78d
from scipy.stats import circnorm_78d
from scipy.stats import circuniform_78d
from scipy.stats import circwraparound_78d
from scipy.stats import circmean_79d
from scipy.stats import circstd_79d
from scipy.stats import circvar_79d
from scipy.stats import circmode_79d
from scipy.stats import circmedian_79d
from scipy.stats import circnorm_79d
from scipy.stats import circuniform_79d
from scipy.stats import circwraparound_79d
from scipy.stats import circmean_80d
from scipy.stats import circstd_80d
from scipy.stats import circvar_80d
from scipy.stats import circmode_80d
from scipy.stats import circmedian_80d
from scipy.stats import circnorm_80d
from scipy.stats import circuniform_80d
from scipy.stats import circwraparound_80d
from scipy.stats import circmean_81d
from scipy.stats import circstd_81d
from scipy.stats import circvar_81d
from scipy.stats import circmode_81d
from scipy.stats import circmedian_81d
from scipy.stats import circnorm_81d
from scipy.stats import circuniform_81d
from scipy.stats import circwraparound_81d
from scipy.stats import circmean_82d
from scipy.stats import circstd_82d
from scipy.stats import circvar_82d
from scipy.stats import circmode_82d
from scipy.stats import circmedian_82d
from scipy.stats import circnorm_82d
from scipy.stats import circuniform_82d
from scipy.stats import circwraparound_82d
from scipy.stats import circmean_83d
from scipy.stats import circstd_83d
from scipy.stats import circvar_83d
from scipy.stats import circmode_83d
from scipy.stats import circmedian_83d
from scipy.stats import circnorm_83d
from scipy.stats import circuniform_83d
from scipy.stats import circwraparound_83d
from scipy.stats import circmean_84d
from scipy.stats import circstd_84d
from scipy.stats import circvar_84d
from scipy.stats import circmode_84d
from scipy.stats import circmedian_84d
from scipy.stats import circnorm_84d
from scipy.stats import circuniform_84d
from scipy.stats import circwraparound_84d
from scipy.stats import circmean_85d
from scipy.stats import circstd_85d
from scipy.stats import circvar_85d
from scipy.stats import circmode_85d
from scipy.stats import circmedian_85d
from scipy.stats import circnorm_85d
from scipy.stats import circuniform_85d
from scipy.stats import circwraparound_85d
from scipy.stats import circmean_86d
from scipy.stats import circstd_86d
from scipy.stats import circvar_86d
from scipy.stats import circmode_86d
from scipy.stats import circmedian_86d
from scipy.stats import circnorm_86d
from scipy.stats import circuniform_86d
from scipy.stats import circwraparound_86d
from scipy.stats import circmean_87d
from scipy.stats import circstd_87d
from scipy.stats import circvar_87d
from scipy.stats import circmode_87d
from scipy.stats import circmedian_87d
from scipy.stats import circnorm_87d
from scipy.stats import circuniform_87d
from scipy.stats import circwraparound_87d
from scipy.stats import circmean_88d
from scipy.stats import circstd_88d
from scipy.stats import circvar_88d
from scipy.stats import circmode_88d
from scipy.stats import circmedian_88d
from scipy.stats import circnorm_88d
from scipy.stats import circuniform_88d
from scipy.stats import circwraparound_88d
from scipy.stats import circmean_89d
from scipy.stats import circstd_89d
from scipy.stats import circvar_89d
from scipy.stats import circmode_89d
from scipy.stats import circmedian_89d
from scipy.stats import circnorm_89d
from scipy.stats import circuniform_89d
from scipy.stats import circwraparound_89d
from scipy.stats import circmean_90d
from scipy.stats import circstd_90d
from scipy.stats import circvar_90d
from scipy.stats import circmode_90d
from scipy.stats import circmedian_90d
from scipy.stats import circnorm_90d
from scipy.stats import circuniform_90d
from scipy.stats import circwraparound_90d
from scipy.stats import circmean_91d
from scipy.stats import circstd_91d
from scipy.stats import circvar_91d
from scipy.stats import circmode_91d
from scipy.stats import circmedian_91d
from scipy.stats import circnorm_91d
from scipy.stats import circuniform_91d
from scipy.stats import circwraparound_91d
from scipy.stats import circmean_92d
from scipy.stats import circstd_92d
from scipy.stats import circvar_92d
from scipy.stats import circmode_92d
from scipy.stats import circmedian_92d
from scipy.stats import circnorm_92d
from scipy.stats import circuniform_92d
from scipy.stats import circwraparound_92d
from scipy.stats import circmean_93d
from scipy.stats import circstd_93d
from scipy.stats import circvar_93d
from scipy.stats import circmode_93d
from scipy.stats import circmedian_93d
from scipy.stats import circnorm_93d
from scipy.stats import circuniform_93d
from scipy.stats import circwraparound_93d
from scipy.stats import circmean_94d
from scipy.stats import circstd_94d
from scipy.stats import circvar_94d
from scipy.stats import circmode_94d
from scipy.stats import circmedian_94d
from scipy.stats import circnorm_94d
from scipy.stats import circuniform_94d
from scipy.stats import circwraparound_94d
from scipy.stats import circmean_95d
from scipy.stats import circstd_95d
from scipy.stats import circvar_95d
from scipy.stats import circmode_95d
from scipy.stats import circmedian_95d
from scipy.stats import circnorm_95d
from scipy.stats import circuniform_95d
from scipy.stats import circwraparound_95d
from scipy.stats import circmean_96d
from scipy.stats import circstd_96d
from scipy.stats import circvar_96d
from scipy.stats import circmode_96d
from scipy.stats import circmedian_96d
from scipy.stats import circnorm_96d
from scipy.stats import circuniform_96d
from scipy.stats import circ