import logging
import numpy as np
import cv2
import torch
from typing import List, Tuple, Dict
from PIL import Image
from torchvision import transforms
from torchvision.transforms.functional import to_tensor
from torchvision.transforms import Compose
from torchvision.transforms import ToPILImage
from torchvision.transforms import Resize
from torchvision.transforms import CenterCrop
from torchvision.transforms import RandomCrop
from torchvision.transforms import RandomHorizontalFlip
from torchvision.transforms import RandomVerticalFlip
from torchvision.transforms import RandomRotation
from torchvision.transforms import ColorJitter
from torchvision.transforms import ToTensor
from torchvision.transforms import Normalize
from torchvision.transforms import InterpolationMode
from torchvision.transforms import RandomAffine
from torchvision.transforms import RandomPerspective
from torchvision.transforms import RandomResizedCrop
from torchvision.transforms import RandomErasing
from torchvision.transforms import InterpolationMode
from torchvision.transforms import ToTensorLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision.transforms import RandomCrop as RandomCropLab
from torchvision.transforms import RandomHorizontalFlip as RandomHorizontalFlipLab
from torchvision.transforms import RandomVerticalFlip as RandomVerticalFlipLab
from torchvision.transforms import RandomRotation as RandomRotationLab
from torchvision.transforms import ColorJitter as ColorJitterLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Normalize as NormalizeLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import RandomAffine as RandomAffineLab
from torchvision.transforms import RandomPerspective as RandomPerspectiveLab
from torchvision.transforms import RandomResizedCrop as RandomResizedCropLab
from torchvision.transforms import RandomErasing as RandomErasingLab
from torchvision.transforms import InterpolationMode as InterpolationModeLab
from torchvision.transforms import ToTensorLab as ToTensorLabLab
from torchvision.transforms import Compose as ComposeLab
from torchvision.transforms import ToPILImage as ToPILImageLab
from torchvision.transforms import Resize as ResizeLab
from torchvision.transforms import CenterCrop as CenterCropLab
from torchvision